<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDMgxRRu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDMgxRRu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDMgxRRu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDMgxRRu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDMgxRRu\App_KernelDevDebugContainer([
    'container.build_hash' => 'DMgxRRu',
    'container.build_id' => 'a0f1b0ff',
    'container.build_time' => 1574934787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDMgxRRu');
